### PR TITLE
Update links in DESCRIPTION

### PR DESCRIPTION
**Pull request by olivroy**

### CODE REVIEW

**Comment by olivroy** [comment]
@jrosen48 for your deps you have to have a space between `>=` and the version

example

```
Matrix (>= 1.4)
```

**Comment by jrosen48** [comment]
thanks for this @olivroy - I made the change in a PR -- https://github.com/konfound-project/konfound/commit/408fedbb676f848735c7d0d6b20c726e11fbabd0

**Comment by olivroy** [comment]
That is good! However, this was just a pointer to address the build failures. The goal of this PR is to correct the links in DESCRIPTION to account for the redirection + improve repo discoverability. https://blog.r-hub.io/2019/12/10/urls/

**Comment by olivroy** [comment]
Hi @jrosen48 , this PR is still valid since the package changed its homepage! Let me know if something is not clear!

**Comment by jrosen48** [comment]
Ah hah! I now see. I'm sorry I didn't review this more carefully! Thanks for this edit! Good samaritan kudos!!! Thanks again.

**Comment by jrosen48** [comment]
thx again

**Pull request merged**
